name: coveralls-ci
on:
  push:
    branches:
      - main
      - tests
  pull_request:
    branches:
      - main
      - tests
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'sbt'
      - name: Run tests
        run: sbt clean coverage test
      - name: Coverage Report
        run: sbt coverageReport
      - name: Coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        uses: coverallsapp/github-action@v2


